
version: "3"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
    links:
      - node
    ports:
      - 80:80
  node:
    build:
      context: .
    depends_on:
      - mongo
  mongo:
    image: mongo:5
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
    mongo_data:
